# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontab_info',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='system_info',
            name='system',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Crontab_info',
        ),
        migrations.DeleteModel(
            name='System_info',
        ),
    ]
