# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cron', '0002_auto_20170222_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='主机IP')),
                ('hostname', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='主机名')),
            ],
        ),
        migrations.CreateModel(
            name='Crontab_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('version', models.CharField(default='', max_length=16, verbose_name='客户端版本')),
                ('user_cron', models.TextField(blank=True, default='', null=True, verbose_name='/etc/spool/cron 信息')),
                ('crontab_file', models.TextField(blank=True, default='', null=True, verbose_name='/etc/crontab 信息')),
                ('cron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cron.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='System_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=64, verbose_name='系统平台')),
                ('sys_type', models.CharField(default='', max_length=16, verbose_name='操作系统')),
                ('distribution', models.CharField(default='', max_length=128, verbose_name='系统发行版')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cron.Agent')),
            ],
        ),
    ]
